# Generated by Django 2.2.7 on 2020-01-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureCar', models.ImageField(upload_to='cars_images/', verbose_name='Фото машины')),
                ('modelsOfCars', models.CharField(max_length=300, verbose_name='Модель')),
                ('classOfCars', models.CharField(max_length=100, verbose_name='Класс трансфера')),
                ('infoOfClass', models.CharField(max_length=300, verbose_name='Информация о классе')),
                ('maxPassenger', models.IntegerField(verbose_name='Максимальное кол-во пассажиров')),
                ('maxBags', models.IntegerField(verbose_name='Максимальное кол-во багажного места')),
                ('priceOfTransfer', models.FloatField(blank=True, null=True, verbose_name='Коэффициент трансфера')),
            ],
            options={
                'verbose_name': 'Класс трансфера',
                'verbose_name_plural': 'Классы трансферов',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя водителя')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email водителя')),
                ('car', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Частый вопрос',
                'verbose_name_plural': 'Частые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='StatusPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_transfer', models.CharField(max_length=128, verbose_name='Откуда')),
                ('time_from', models.CharField(max_length=128, verbose_name='Дата отправления и время')),
                ('to_transfer', models.CharField(max_length=128, verbose_name='Куда')),
                ('passenger', models.IntegerField(default=1, verbose_name='Кол-во пассажиров')),
                ('children', models.BooleanField(verbose_name='Есть-ли дети')),
                ('return_transfer', models.BooleanField(verbose_name='Есть-ли обратный трансфер')),
                ('time_return_transfer', models.CharField(blank=True, max_length=128, null=True, verbose_name='Время обратного трансфера')),
                ('children_passenger', models.IntegerField(blank=True, null=True, verbose_name='Кол-во детей')),
                ('chair_small', models.IntegerField(blank=True, default=0, null=True, verbose_name='0-13 кг')),
                ('chair_middle', models.IntegerField(blank=True, default=0, null=True, verbose_name='9-18 кг')),
                ('chair_large', models.IntegerField(blank=True, default=0, null=True, verbose_name='15-36 кг')),
                ('name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid', models.BooleanField(blank=True, null=True, verbose_name='Оплачен')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('price_company', models.IntegerField(blank=True, null=True, verbose_name='Себестоимость')),
                ('class_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czech.Car', verbose_name='Класс транспорта')),
                ('drivers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='czech.Drivers', verbose_name='Водитель')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='czech.Status')),
                ('status_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='czech.StatusPay', verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
