# Generated by Django 2.2.7 on 2019-12-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
