# Generated by Django 2.2.7 on 2020-01-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drivers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Drivers', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='class_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Car', verbose_name='Класс транспорта'),
        ),
    ]
