# Generated by Django 2.2.7 on 2020-01-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200108_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_active',
        ),
    ]
